// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package main

import (
	config2 "admin-user/rpc/internal/config"
	server2 "admin-user/rpc/internal/server"
	svc2 "admin-user/rpc/internal/svc"
	user2 "admin-user/rpc/user"
	"flag"
	"fmt"
	"github.com/tal-tech/go-zero/core/logx"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/dev.yaml", "the config file")

func main() {
	flag.Parse()

	var c config2.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc2.NewServiceContext(c)
	srv := server2.NewUserServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		user2.RegisterUserServer(grpcServer, srv)
	})
	defer s.Stop()

	// 关闭输出的统计日志
	logx.DisableStat()

	// 初始化mysql默认数据
	//Initialization2.InitializationData()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
