// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"admin-user/rpc/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ApiInfo                     = user.ApiInfo
	LoginOutRequest             = user.LoginOutRequest
	FindAdminByIdsRequest       = user.FindAdminByIdsRequest
	GetPermissionResponse       = user.GetPermissionResponse
	DeleteRoleResponse          = user.DeleteRoleResponse
	AddAdminRequest             = user.AddAdminRequest
	FindRoleByIdsResponse       = user.FindRoleByIdsResponse
	AddBatchApiRequest          = user.AddBatchApiRequest
	LoginOutResponse            = user.LoginOutResponse
	GetAdminResponse            = user.GetAdminResponse
	FindApiByIdsResponse        = user.FindApiByIdsResponse
	EditAdminRequest            = user.EditAdminRequest
	DeleteRoleRequest           = user.DeleteRoleRequest
	GetApiRequest               = user.GetApiRequest
	GetUserInfoRequest          = user.GetUserInfoRequest
	DeleteAdminRequest          = user.DeleteAdminRequest
	AddPermissionRequest        = user.AddPermissionRequest
	UpdatePasswordRequest       = user.UpdatePasswordRequest
	AddPermissionResponse       = user.AddPermissionResponse
	DeleteApiRequest            = user.DeleteApiRequest
	UpdatePasswordResponse      = user.UpdatePasswordResponse
	GetRoleRequest              = user.GetRoleRequest
	GetPermissionRequest        = user.GetPermissionRequest
	AddRoleResponse             = user.AddRoleResponse
	EditPermissionResponse      = user.EditPermissionResponse
	GetAdminRequest             = user.GetAdminRequest
	AddApiResponse              = user.AddApiResponse
	FindPermissionByIdsResponse = user.FindPermissionByIdsResponse
	DeletePermissionRequest     = user.DeletePermissionRequest
	AddBatchApiResponse         = user.AddBatchApiResponse
	LoginResponse               = user.LoginResponse
	AdminInfo                   = user.AdminInfo
	AddRoleRequest              = user.AddRoleRequest
	DeletePermissionResponse    = user.DeletePermissionResponse
	CheckPermissionResponse     = user.CheckPermissionResponse
	EditApiResponse             = user.EditApiResponse
	GetUserInfoResponse         = user.GetUserInfoResponse
	RoleInfo                    = user.RoleInfo
	EditPermissionRequest       = user.EditPermissionRequest
	FindPermissionByIdsRequest  = user.FindPermissionByIdsRequest
	DeleteApiResponse           = user.DeleteApiResponse
	LoginRequest                = user.LoginRequest
	CheckPermissionRequest      = user.CheckPermissionRequest
	GetRoleResponse             = user.GetRoleResponse
	PermissionInfo              = user.PermissionInfo
	EditAdminResponse           = user.EditAdminResponse
	DeleteAdminResponse         = user.DeleteAdminResponse
	EditRoleResponse            = user.EditRoleResponse
	EditRoleRequest             = user.EditRoleRequest
	GetApiResponse              = user.GetApiResponse
	FindApiByIdsRequest         = user.FindApiByIdsRequest
	AddApiRequest               = user.AddApiRequest
	EditApiRequest              = user.EditApiRequest
	FindAdminByIdsResponse      = user.FindAdminByIdsResponse
	AddAdminResponse            = user.AddAdminResponse
	FindRoleByIdsRequest        = user.FindRoleByIdsRequest

	User interface {
		//  user
		Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error)
		//  account
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest) (*GetUserInfoResponse, error)
		LoginOut(ctx context.Context, in *LoginOutRequest) (*LoginOutResponse, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
		CheckPermission(ctx context.Context, in *CheckPermissionRequest) (*CheckPermissionResponse, error)
		//  admin
		GetAdmin(ctx context.Context, in *GetAdminRequest) (*GetAdminResponse, error)
		AddAdmin(ctx context.Context, in *AddAdminRequest) (*AddAdminResponse, error)
		EditAdmin(ctx context.Context, in *EditAdminRequest) (*EditAdminResponse, error)
		DeleteAdmin(ctx context.Context, in *DeleteAdminRequest) (*DeleteAdminResponse, error)
		FindAdminByIds(ctx context.Context, in *FindAdminByIdsRequest) (*FindAdminByIdsResponse, error)
		//  role
		GetRole(ctx context.Context, in *GetRoleRequest) (*GetRoleResponse, error)
		AddRole(ctx context.Context, in *AddRoleRequest) (*AddRoleResponse, error)
		EditRole(ctx context.Context, in *EditRoleRequest) (*EditRoleResponse, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest) (*DeleteRoleResponse, error)
		FindRoleByIds(ctx context.Context, in *FindRoleByIdsRequest) (*FindRoleByIdsResponse, error)
		//  permission
		GetPermission(ctx context.Context, in *GetPermissionRequest) (*GetPermissionResponse, error)
		AddPermission(ctx context.Context, in *AddPermissionRequest) (*AddPermissionResponse, error)
		EditPermission(ctx context.Context, in *EditPermissionRequest) (*EditPermissionResponse, error)
		DeletePermission(ctx context.Context, in *DeletePermissionRequest) (*DeletePermissionResponse, error)
		FindPermissionByIds(ctx context.Context, in *FindPermissionByIdsRequest) (*FindPermissionByIdsResponse, error)
		//  api
		GetApi(ctx context.Context, in *GetApiRequest) (*GetApiResponse, error)
		AddApi(ctx context.Context, in *AddApiRequest) (*AddApiResponse, error)
		BatchApi(ctx context.Context, in *AddBatchApiRequest) (*AddBatchApiResponse, error)
		EditApi(ctx context.Context, in *EditApiRequest) (*EditApiResponse, error)
		DeleteApi(ctx context.Context, in *DeleteApiRequest) (*DeleteApiResponse, error)
		FindApiByIds(ctx context.Context, in *FindApiByIdsRequest) (*FindApiByIdsResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

//  user
func (m *defaultUser) Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

//  account
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in)
}

func (m *defaultUser) LoginOut(ctx context.Context, in *LoginOutRequest) (*LoginOutResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginOut(ctx, in)
}

func (m *defaultUser) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest) (*UpdatePasswordResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in)
}

func (m *defaultUser) CheckPermission(ctx context.Context, in *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckPermission(ctx, in)
}

//  admin
func (m *defaultUser) GetAdmin(ctx context.Context, in *GetAdminRequest) (*GetAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAdmin(ctx, in)
}

func (m *defaultUser) AddAdmin(ctx context.Context, in *AddAdminRequest) (*AddAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddAdmin(ctx, in)
}

func (m *defaultUser) EditAdmin(ctx context.Context, in *EditAdminRequest) (*EditAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditAdmin(ctx, in)
}

func (m *defaultUser) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest) (*DeleteAdminResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteAdmin(ctx, in)
}

func (m *defaultUser) FindAdminByIds(ctx context.Context, in *FindAdminByIdsRequest) (*FindAdminByIdsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindAdminByIds(ctx, in)
}

//  role
func (m *defaultUser) GetRole(ctx context.Context, in *GetRoleRequest) (*GetRoleResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetRole(ctx, in)
}

func (m *defaultUser) AddRole(ctx context.Context, in *AddRoleRequest) (*AddRoleResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddRole(ctx, in)
}

func (m *defaultUser) EditRole(ctx context.Context, in *EditRoleRequest) (*EditRoleResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditRole(ctx, in)
}

func (m *defaultUser) DeleteRole(ctx context.Context, in *DeleteRoleRequest) (*DeleteRoleResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteRole(ctx, in)
}

func (m *defaultUser) FindRoleByIds(ctx context.Context, in *FindRoleByIdsRequest) (*FindRoleByIdsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindRoleByIds(ctx, in)
}

//  permission
func (m *defaultUser) GetPermission(ctx context.Context, in *GetPermissionRequest) (*GetPermissionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetPermission(ctx, in)
}

func (m *defaultUser) AddPermission(ctx context.Context, in *AddPermissionRequest) (*AddPermissionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddPermission(ctx, in)
}

func (m *defaultUser) EditPermission(ctx context.Context, in *EditPermissionRequest) (*EditPermissionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditPermission(ctx, in)
}

func (m *defaultUser) DeletePermission(ctx context.Context, in *DeletePermissionRequest) (*DeletePermissionResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeletePermission(ctx, in)
}

func (m *defaultUser) FindPermissionByIds(ctx context.Context, in *FindPermissionByIdsRequest) (*FindPermissionByIdsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindPermissionByIds(ctx, in)
}

//  api
func (m *defaultUser) GetApi(ctx context.Context, in *GetApiRequest) (*GetApiResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetApi(ctx, in)
}

func (m *defaultUser) AddApi(ctx context.Context, in *AddApiRequest) (*AddApiResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddApi(ctx, in)
}

func (m *defaultUser) BatchApi(ctx context.Context, in *AddBatchApiRequest) (*AddBatchApiResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.BatchApi(ctx, in)
}

func (m *defaultUser) EditApi(ctx context.Context, in *EditApiRequest) (*EditApiResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditApi(ctx, in)
}

func (m *defaultUser) DeleteApi(ctx context.Context, in *DeleteApiRequest) (*DeleteApiResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteApi(ctx, in)
}

func (m *defaultUser) FindApiByIds(ctx context.Context, in *FindApiByIdsRequest) (*FindApiByIdsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FindApiByIds(ctx, in)
}
