Name: user.rpc
ListenOn: 0.0.0.0:8002
Timeout: 3000         # 超时控制 单位:毫秒
CpuThreshold: 900     # cpu降载阈值，默认900，可允许设置范围0到1000
# etcd 相关配置
Etcd:
  Hosts:
  - docker.for.mac.host.internal:2379
  Key: user.rpc
# redis 配置
Redis:
  Host: docker.for.mac.host.internal:6379  # 地址
  Password: "123456"    # 密码
  DB: 0
  DialTimeOut: 60s
  ReadTimeOut: 2s
  WriteTimeOut: 2s
  PoolTimeOut: 30s
  PoolSize: 60
# mysql 配置
Mysql:
  Name: laihua_user     # db name
  Addr: docker.for.mac.host.internal:3306  # db 地址
  UserName: root        # 用户名
  Password: "123456"      # 密码
  ShowLog: true         # 是否打印SQL日志
  MaxIdleConn: 10       # 最大闲置的连接数
  MaxOpenConn: 60       # 最大打开的连接数
  ConnMaxLifeTime: 60   # 连接重用的最大时间，单位分钟
# jwt 配置
AuthConf:
  AccessSecret: ad879037-c7a4-4063-9236-6bfc35d54b7d  # jwt token的密钥
  AccessExpire: 86400 # jwtToken 有效时间 单位：秒  ps：改这里记得改退出登陆和AuthMiddleware的逻辑（token黑名单key过期时间）